const express = require("express")
const { createTask, updateTask, deleteTask, getMyTask, getMyTaskAsManager, getMyTaskAsContributor, getAllTask, checkingTask, countTaskAsDone, countTaskAsNotDone, countTaskAsOutOfDate, countTaskAll, sortTask } = require("../controllers/Task")
const isAuthenticated = require("../middleware/auth")
const router = express.Router()
router.route("/createtask").post(isAuthenticated, createTask)
router.route("/updatetask").put(isAuthenticated, updateTask)
router.route("/deletetask").delete(isAuthenticated, deleteTask)
router.route("/mytask").get(isAuthenticated, getMyTask)
router.route("/mytaskasmanager").get(isAuthenticated, getMyTaskAsManager)
router.route("/mytaskascontributor").get(isAuthenticated, getMyTaskAsContributor)
router.route("/alltask").get(isAuthenticated, getAllTask)
router.route("/checkingtask").post(isAuthenticated, checkingTask)
router.route("/counttaskasdone").get(isAuthenticated, countTaskAsDone)
router.route("/counttaskasnotdone").get(isAuthenticated, countTaskAsNotDone)
router.route("/counttaskasoutofdone").get(isAuthenticated, countTaskAsOutOfDate)
router.route("/counttaskall").get(isAuthenticated, countTaskAll)
router.route("/sorttask").get(isAuthenticated, sortTask)
module.exports = router