const express = require("express")
const { createTimesheet, checkin, checkout, getTop5, getMyRank, filterTimesheetDataByToday, filterTimesheetDataByYesterday, filterTimesheetDataByThisWeek, filterTimesheetDataByLastWeek, filterTimesheetDataByThisMonth, filterTimesheetDataByLastMonth } = require("../controllers/Timesheet")
const isAuthenticated = require("../middleware/auth")
const router = express.Router()
router.route("/createtimesheet").post(isAuthenticated, createTimesheet)
router.route("/checkin").post(isAuthenticated, checkin)
router.route("/checkout").post(isAuthenticated, checkout)
router.route("/gettop5").get(getTop5)
router.route("/rank").get(isAuthenticated, getMyRank)
router.route("/filtertimesheetdatabytoday").get(isAuthenticated, filterTimesheetDataByToday)
router.route("/filtertimesheetdatabyyesterday").get(isAuthenticated, filterTimesheetDataByYesterday)
router.route("/filtertimesheetdatabythisweek").get(isAuthenticated, filterTimesheetDataByThisWeek)
router.route("/filtertimesheetdatabylastweek").get(isAuthenticated, filterTimesheetDataByLastWeek)
router.route("/filtertimesheetdatabythismonth").get(isAuthenticated, filterTimesheetDataByThisMonth)
router.route("/filtertimesheetdatabylastmonth").get(isAuthenticated, filterTimesheetDataByLastMonth)
module.exports = router