const express = require("express")
const { register, verify, login, logout, getMyProfile, getAllProfile, updateProfile, updateAvatar, deleteProfile, updatePassword, forgetPassword, resetPassword, phonePassword } = require("../controllers/User")
const isAuthenticated = require("../middleware/auth")
const router = express.Router()
router.route("/register").post(isAuthenticated, register)
router.route("/verify").post(isAuthenticated, verify)
router.route("/login").post(login)
router.route("/logout").post(logout)
router.route("/myprofile").get(isAuthenticated, getMyProfile)
router.route("/profiles").get(getAllProfile)
router.route("/updateprofile").put(isAuthenticated, updateProfile)
router.route("/updateavatar").put(isAuthenticated, updateAvatar)
router.route("/deleteprofile").delete(isAuthenticated, deleteProfile)
router.route("/updatepassword").put(isAuthenticated, updatePassword)
router.route("/forgetpassword").post(forgetPassword)
router.route("/phonepassword").post(phonePassword)
router.route("/resetpassword").put(resetPassword)
router.route("/updateadmin").put()
module.exports = router